journals = {"Wissensrepresentation und Schlussfolgern": ["autonomous agents and multi-agent systems",
                                                         "journal of automated reasoning"],
            "Unsicherheit und Schlussfolgern": [],
            "Maschinelles Lernen": ["machine learning",
                                    "neural networks : the official journal of the international neural network society",
                                    "ai magazine",
                                    "artif. intell.",
                                    "ieee transactions on neural networks and learning systems",
                                    "ieee transactions on neural networks",
                                    "journal of machine learning research",
                                    "fourth ieee international conference on data mining (icdm'04)",
                                    "fifth ieee international conference on data mining (icdm'05)",
                                    "sixth international conference on data mining (icdm'06)",
                                    "seventh ieee international conference on data mining (icdm 2007)",
                                    "2008 eighth ieee international conference on data mining",
                                    "2009 ninth ieee international conference on data mining",
                                    "2010 ieee international conference on data mining",
                                    "2011 ieee 11th international conference on data mining",
                                    "2012 ieee 12th international conference on data mining",
                                    "2013 ieee 13th international conference on data mining",
                                    "2014 ieee international conference on data mining",
                                    "2015 ieee international conference on data mining",
                                    "2016 ieee 16th international conference on data mining (icdm)",
                                    "2017 ieee international conference on data mining (icdm)",
                                    "ieee transactions on knowledge and data engineering",
                                    "neural networks",
                                    "data mining and knowledge discovery",
                                    "2004 ieee international joint conference on neural networks (ieee cat. no.04ch37541)",
                                    "2007 international joint conference on neural networks",
                                    "2008 ieee international joint conference on neural networks (ieee world congress on computational intelligence)",
                                    "2009 international joint conference on neural networks",
                                    "the 2010 international joint conference on neural networks (ijcnn)",
                                    "the 2011 international joint conference on neural networks",
                                    "the 2012 international joint conference on neural networks (ijcnn)",
                                    "the 2013 international joint conference on neural networks (ijcnn)",
                                    "2014 international joint conference on neural networks (ijcnn)",
                                    "2015 international joint conference on neural networks (ijcnn)",
                                    "2016 international joint conference on neural networks (ijcnn)",
                                    "2017 international joint conference on neural networks (ijcnn)",
                                    "neural processing letters",
                                    "information retrieval",
                                    "information retrieval journal"],
            "Wahrnemung und Sehen": ["2005 ieee computer society conference on computer vision and pattern recognition (cvpr'05)",
                                     "2006 ieee computer society conference on computer vision and pattern recognition (cvpr'06)",
                                     "2007 ieee conference on computer vision and pattern recognition",
                                     "2008 ieee conference on computer vision and pattern recognition",
                                     "2009 ieee conference on computer vision and pattern recognition",
                                     "2010 ieee computer society conference on computer vision and pattern recognition",
                                     "cvpr 2011",
                                     "2012 ieee conference on computer vision and pattern recognition",
                                     "2013 ieee conference on computer vision and pattern recognition",
                                     "2014 ieee conference on computer vision and pattern recognition",
                                     "2015 ieee conference on computer vision and pattern recognition (cvpr)",
                                     "2016 ieee conference on computer vision and pattern recognition (cvpr)",
                                     "2017 ieee conference on computer vision and pattern recognition (cvpr)",
                                     "2015 ieee international conference on computer vision (iccv)",
                                     "2017 ieee international conference on computer vision (iccv)",
                                     "ieee transactions on pattern analysis and machine intelligence",
                                     "international journal of computer vision",
                                     "computer vision and image understanding"
                                     ],
            "Robotik": ["the international journal of robotics research",
                        "ieee transactions on robotics",
                        "2004 ieee/rsj international conference on intelligent robots and systems (iros) (ieee cat. no.04ch37566)",
                        "2005 ieee/rsj international conference on intelligent robots and systems",
                        "2006 ieee/rsj international conference on intelligent robots and systems",
                        "2007 ieee/rsj international conference on intelligent robots and systems",
                        "2008 ieee/rsj international conference on intelligent robots and systems",
                        "2009 ieee/rsj international conference on intelligent robots and systems",
                        "2010 ieee/rsj international conference on intelligent robots and systems",
                        "2011 ieee/rsj international conference on intelligent robots and systems",
                        "2012 ieee/rsj international conference on intelligent robots and systems",
                        "2014 ieee/rsj international conference on intelligent robots and systems",
                        "2013 ieee/rsj international conference on intelligent robots and systems",
                        "2015 ieee/rsj international conference on intelligent robots and systems (iros)",
                        "2016 ieee/rsj international conference on intelligent robots and systems (iros)",
                        "2017 ieee/rsj international conference on intelligent robots and systems (iros)",
                        "robotics and autonomous systems"
                        ]}

 #################################################

venues = {"Wissensrepresentation und Schlussfolgern": ["autonomous agents and multi-agent systems",
                                                       "icaps",
                                                       "journal of automated reasoning",
                                                       "jelia",  # European Conf. on Logics and Artificial Intelligence
                                                       "tableaux",
                                                       "iccbr",
                                                       "tark",
                                                       "iclp"],
          "Unsicherheit und Schlussfolgern": ["uai"],
          "Maschinelles Lernen": ["nips",
                                  "icml",
                                  "aaai",
                                  "ijcai",
                                  "ai magazine",
                                  "machine learning",
                                  "ieee transactions on neural networks and learning systems",
                                  "ieee transactions on neural networks",
                                  "kdd",  # ???
                                  "sigir",
                                  "journal of machine learning research",
                                  "fourth ieee international conference on data mining (icdm'04)",
                                  "fifth ieee international conference on data mining (icdm'05)",
                                  "sixth international conference on data mining (icdm'06)",
                                  "seventh ieee international conference on data mining (icdm 2007)",
                                  "2008 eighth ieee international conference on data mining",
                                  "2009 ninth ieee international conference on data mining",
                                  "2010 ieee international conference on data mining",
                                  "2011 ieee 11th international conference on data mining",
                                  "2012 ieee 12th international conference on data mining",
                                  "2013 ieee 13th international conference on data mining",
                                  "2014 ieee international conference on data mining",
                                  "2015 ieee international conference on data mining",
                                  "2016 ieee 16th international conference on data mining (icdm)",
                                  "2017 ieee international conference on data mining (icdm)",
                                  "ieee transactions on knowledge and data engineering",
                                  "neural networks",
                                  "cikm",
                                  "aistats",
                                  "data mining and knowledge discovery",
                                  "sdm",
                                  "ecml/pkdd",
                                  "ecir",
                                  "pakdd",
                                  "recsys",
                                  "2004 ieee international joint conference on neural networks (ieee cat. no.04ch37541)",
                                  "2007 international joint conference on neural networks",
                                  "2008 ieee international joint conference on neural networks (ieee world congress on computational intelligence)",
                                  "2009 international joint conference on neural networks",
                                  "the 2010 international joint conference on neural networks (ijcnn)",
                                  "the 2011 international joint conference on neural networks",
                                  "the 2012 international joint conference on neural networks (ijcnn)",
                                  "the 2013 international joint conference on neural networks (ijcnn)",
                                  "2014 international joint conference on neural networks (ijcnn)",
                                  "2015 international joint conference on neural networks (ijcnn)",
                                  "2016 international joint conference on neural networks (ijcnn)",
                                  "2017 international joint conference on neural networks (ijcnn)",
                                  "neural processing letters",
                                  "information retrieval",
                                  "information retrieval journal",
                                  "icann",
                                  "ilp"],
          "Wahrnemung und Sehen": ["2005 ieee computer society conference on computer vision and pattern recognition (cvpr'05)",
                                   "2006 ieee computer society conference on computer vision and pattern recognition (cvpr'06)",
                                   "2007 ieee conference on computer vision and pattern recognition",
                                   "2008 ieee conference on computer vision and pattern recognition",
                                   "2009 ieee conference on computer vision and pattern recognition",
                                   "2010 ieee computer society conference on computer vision and pattern recognition",
                                   "cvpr 2011",
                                   "2012 ieee conference on computer vision and pattern recognition",
                                   "2013 ieee conference on computer vision and pattern recognition",
                                   "2014 ieee conference on computer vision and pattern recognition",
                                   "2015 ieee conference on computer vision and pattern recognition (cvpr)",
                                   "2016 ieee conference on computer vision and pattern recognition (cvpr)",
                                   "2017 ieee conference on computer vision and pattern recognition (cvpr)",
                                   "cvpr",
                                   "iccv",
                                   "2015 ieee international conference on computer vision (iccv)",
                                   "2017 ieee international conference on computer vision (iccv)",
                                   "ieee transactions on pattern analysis and machine intelligence",
                                   "eccv",
                                   "international journal of computer vision",
                                   "computer vision and image understanding"],
          "Verstehen und Generierung von natürlicher Sprache": ["acl",
                                                                "naacl",
                                                                "emnlp",
                                                                "coling",
                                                                "eacl",
                                                                "conll",
                                                                "acl/ijcnlp",
                                                                "ijcnlp",
                                                                "robotics: science and systems"
                                                                ],
          "Robotik": ["ieee transactions on robotics",
                      "2004 ieee/rsj international conference on intelligent robots and systems (iros) (ieee cat. no.04ch37566)",
                      "2005 ieee/rsj international conference on intelligent robots and systems",
                      "2006 ieee/rsj international conference on intelligent robots and systems",
                      "2007 ieee/rsj international conference on intelligent robots and systems",
                      "2008 ieee/rsj international conference on intelligent robots and systems",
                      "2009 ieee/rsj international conference on intelligent robots and systems",
                      "2010 ieee/rsj international conference on intelligent robots and systems",
                      "2011 ieee/rsj international conference on intelligent robots and systems",
                      "2012 ieee/rsj international conference on intelligent robots and systems",
                      "2014 ieee/rsj international conference on intelligent robots and systems",
                      "2013 ieee/rsj international conference on intelligent robots and systems",
                      "2015 ieee/rsj international conference on intelligent robots and systems (iros)",
                      "2016 ieee/rsj international conference on intelligent robots and systems (iros)",
                      "2017 ieee/rsj international conference on intelligent robots and systems (iros)",
                      "robotics and autonomous systems"
                      ]}